[operators]
[operators.sim_ground]
    class = "toast.ops.sim_ground.SimGround"
    API = 0 # Internal interface version for this operator
    azimuth = "azimuth" # Observation shared key for Azimuth
    boresight_azel = "boresight_azel" # Observation shared key for boresight AZ/EL
    boresight_radec = "boresight_radec" # Observation shared key for boresight RA/DEC
    det_data = "signal" # Observation detdata key to initialize
    det_data_units = "unit K" # Output units if creating detector data
    det_flags = "flags" # Observation detdata key for flags to initialize
    detset_key = "pixel" # If specified, use this column of the focalplane detector_data to group detectors
    distribute_time = false # Distribute observation data along the time axis rather than detector axis
    el_mod_amplitude = "1.00000000000000e+00 deg" # Range of elevation modulation
    el_mod_rate = "0.00000000000000e+00 Hz" # Modulate elevation continuously at this rate
    el_mod_sine = false # Modulate elevation with a sine wave instead of a triangle wave
    el_mod_step = "0.00000000000000e+00 deg" # Amount to step elevation after each left-right scan pair
    elevation = "elevation" # Observation shared key for Elevation
    elnod_end = false # Perform an el-nod after the scan
    elnod_every_scan = false # Perform el nods every scan
    elnod_interval = "elnod" # Interval name for elnods
    elnod_mask = 7 # Bit mask to raise elevation nod flags with
    elnod_start = false # Perform an el-nod before the scan
    elnods = [] # List of relative el_nods
    enabled = true # If True, this class instance is marked as enabled
    fix_rate_on_sky = true # If True, `scan_rate_az` is given in sky coordinates and azimuthal rate on mount will be adjusted to meet it.  If False, `scan_rate_az` is used as the mount azimuthal rate.
    hwp_angle = "None" # Observation shared key for HWP angle
    hwp_rpm = "None" # The rate (in RPM) of the HWP rotation
    hwp_step = "None" # For stepped HWP, the angle of each step
    hwp_step_time = "None" # For stepped HWP, the time between steps
    invalid_mask = 1 # Bit mask to raise invalid flags with
    leftright_mask = 8 # Bit mask to raise left-to-right flags with
    max_pwv = "None" # Maximum PWV for the simulated weather.
    median_weather = false # Use median weather parameters instead of sampling from the distributions
    name = "sim_ground" # The 'name' of this class instance
    position = "position" # Observation shared key for position
    randomize_phase = false # If True, the Constant Elevation Scan will begin at a randomized phase.
    realization = 0 # The realization index
    rightleft_mask = 16 # Bit mask to raise right-to-left flags with
    scan_accel_az = "2.58 deg / s2" # Mount scanning rate acceleration for turnarounds
    scan_accel_el = "1.00000000000000e+00 deg / s2" # Mount elevation rate acceleration.
    scan_cosecant_modulation = true # Modulate the scan rate according to 1/sin(az) for uniform depth
    scan_leftright_interval = "scan_leftright" # Interval name for left to right scans
    scan_rate_az = "0.5 deg / s" # The sky azimuth scanning rate
    scan_rate_el = "1.00000000000000e+00 deg / s" # The sky elevation scanning rate
    scan_rightleft_interval = "scan_rightleft" # Interval name for right to left scans
    scanning_interval = "scanning" # Interval name for scanning
    schedule = "None" # Instance of a GroundSchedule
    shared_flags = "flags" # Observation shared key for common flags
    sun_angle_min = "9.00000000000000e+01 deg" # Minimum angular distance for the scan and the Sun
    sun_close_distance = "4.50000000000000e+01 deg" # 'Sun close' flagging distance
    sun_close_interval = "sun_close" # Interval name for times when the sun is close
    sun_close_mask = 64 # Bit mask to raise Sun close flags with
    sun_up_interval = "sun_up" # Interval name for times when the sun is up
    sun_up_mask = 32 # Bit mask to raise Sun up flags with
    telescope = "None" # This must be an instance of a Telescope
    throw_interval = "throw" # Interval name for scan + turnaround intervals
    throw_leftright_interval = "throw_leftright" # Interval name for left to right scans + turnarounds
    throw_rightleft_interval = "throw_rightleft" # Interval name for right to left scans + turnarounds
    times = "times" # Observation shared key for timestamps
    timezone = 0 # The (integer) timezone offset in hours from UTC to apply to schedule
    turn_leftright_interval = "turn_leftright" # Interval name for turnarounds after left to right scans
    turn_rightleft_interval = "turn_rightleft" # Interval name for turnarounds after right to left scans
    turnaround_interval = "turnaround" # Interval name for turnarounds
    turnaround_mask = 3 # Bit mask to raise turnaround flags with
    velocity = "velocity" # Observation shared key for velocity
    weather = "atacama" # Name of built-in weather site (e.g. 'atacama', 'south_pole') or path to HDF5 file
